"""Initial tables

Revision ID: eca0dad3bf24
Revises: 
Create Date: 2024-10-21 16:58:37.999115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca0dad3bf24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('coach_client_relationships',
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    op.create_index(op.f('ix_coach_client_relationships_relationship_id'), 'coach_client_relationships', ['relationship_id'], unique=False)
    op.create_table('nutrition_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan', sa.Text(), nullable=True),
    sa.Column('calories_per_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_id'], ['coach_client_relationships.relationship_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_nutrition_plans_plan_id'), 'nutrition_plans', ['plan_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_frequency', sa.String(length=50), nullable=True),
    sa.Column('next_payment_due', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_id'], ['coach_client_relationships.relationship_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_payment_plans_plan_id'), 'payment_plans', ['plan_id'], unique=False)
    op.create_table('workout_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=100), nullable=True),
    sa.Column('workout_duration', sa.Integer(), nullable=True),
    sa.Column('frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['relationship_id'], ['coach_client_relationships.relationship_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_workout_plans_plan_id'), 'workout_plans', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_plans_plan_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_payment_plans_plan_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_nutrition_plans_plan_id'), table_name='nutrition_plans')
    op.drop_table('nutrition_plans')
    op.drop_index(op.f('ix_coach_client_relationships_relationship_id'), table_name='coach_client_relationships')
    op.drop_table('coach_client_relationships')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
